-- 002_sellar.sql — deja constancia de que el esquema ya trae las 73 migraciones.
--
-- GENERADO por bin/gen_base.sh. Sin esto, una base creada desde el baseline
-- creería que le faltan 73 migraciones; con esto, bin/migrar.sh sabe que la
-- primera pendiente es la 074.

CREATE TABLE IF NOT EXISTS schema_migraciones (
  archivo     text PRIMARY KEY,
  aplicada_en timestamptz NOT NULL DEFAULT now());

INSERT INTO schema_migraciones (archivo) VALUES
  ('001_nucleo.sql'),
  ('002_contenido.sql'),
  ('003_semillas.sql'),
  ('004_ingesta.sql'),
  ('005_matching.sql'),
  ('006_calculos.sql'),
  ('007_fix_mapeo_pos.sql'),
  ('008_ejecucion_operacion.sql'),
  ('009_fix_validar_cifras.sql'),
  ('010_prompt_pdf_ventas.sql'),
  ('011_modelo_deepseek_v4.sql'),
  ('012_router.sql'),
  ('013_plantillas_router.sql'),
  ('014_mantenimiento_notif.sql'),
  ('015_router_admin.sql'),
  ('016_fix_jsonb_literales.sql'),
  ('017_ingesta_tabular.sql'),
  ('018_plantillas_ingesta.sql'),
  ('019_ingesta_encadenado.sql'),
  ('020_informe_en_chat.sql'),
  ('021_informe_texto_plano.sql'),
  ('022_plantillas_html.sql'),
  ('023_teclados.sql'),
  ('024_router_botones.sql'),
  ('025_informe_estructurado.sql'),
  ('026_fix_cifras_miles.sql'),
  ('027_teclado_plano.sql'),
  ('028_prompt_cifras_cupo.sql'),
  ('029_servicios_identidades_conocimiento.sql'),
  ('030_servicio_consulta.sql'),
  ('031_estructura_seca_en_sql.sql'),
  ('032_entrega_por_servicio.sql'),
  ('033_portal.sql'),
  ('034_ejecucion_privada.sql'),
  ('035_portal_movimientos.sql'),
  ('036_cartera.sql'),
  ('037_portal_cartera.sql'),
  ('038_portal_nit.sql'),
  ('039_funciones_privadas_de_verdad.sql'),
  ('040_cotizador.sql'),
  ('041_cobro.sql'),
  ('042_confirmar_carga.sql'),
  ('043_mercado_compras.sql'),
  ('044_whatsapp.sql'),
  ('045_menu_modulos.sql'),
  ('046_conversacion_directa.sql'),
  ('047_informe_prescriptivo.sql'),
  ('048_formatos_reales.sql'),
  ('049_boton_analizar_en_carga.sql'),
  ('050_negocio_automatico.sql'),
  ('051_consentimiento_y_plan_free.sql'),
  ('052_aviso_ia_en_consulta.sql'),
  ('053_historia_completa.sql'),
  ('054_inventario_declarado.sql'),
  ('055_impacto_tipado.sql'),
  ('056_router_modular.sql'),
  ('057_limpieza.sql'),
  ('058_snapshot_negocio.sql'),
  ('059_recomendaciones_persistentes.sql'),
  ('060_reglas_comparativas.sql'),
  ('061_perfil_negocio.sql'),
  ('062_consulta_sobre_numeros.sql'),
  ('063_intenciones_consulta.sql'),
  ('064_acciones.sql'),
  ('065_pedido.sql'),
  ('066_resultado.sql'),
  ('067_alertas.sql'),
  ('068_informe_periodico.sql'),
  ('069_cartera_liquidez.sql'),
  ('070_menus_que_no_saturan.sql'),
  ('071_carga_sin_perdida.sql'),
  ('072_informe_declara_base.sql'),
  ('073_ingesta_sin_modelo.sql')
ON CONFLICT (archivo) DO NOTHING;
